// Glifos rúnicos (Unicode, Noto Sans Runic), por id de runa,
// conforme o DATA() do handoff. O Wyrd (runa branca) é o losango.
export const GLYPH: Record<number, string> = {
  0: "ᚠ",
  1: "ᚢ",
  2: "ᚦ",
  3: "ᚨ",
  4: "ᚱ",
  5: "ᚲ",
  6: "ᚷ",
  7: "ᚹ",
  8: "ᚺ",
  9: "ᚾ",
  10: "ᛁ",
  11: "ᛃ",
  12: "ᛇ",
  13: "ᛈ",
  14: "ᛉ",
  15: "ᛊ",
  16: "ᛏ",
  17: "ᛒ",
  18: "ᛖ",
  19: "ᛗ",
  20: "ᛚ",
  21: "ᛜ",
  22: "ᛞ",
  23: "ᛟ",
  24: "◇",
};
