import type { Rune } from "./types";

// As 25 runas do Modulo Branco, dados tal e qual o prototipo.
// ed = nome do Eduardo (anglo-saxonico); mod = nome moderno (Elder Futhark).
export const RUNES: Rune[] = [
  {
    id: 0, ed: "Feoh", mod: "Fehu", letter: "F", deity: "Freyr", epi: "Pureza e Elevação", type: "Deus",
    elem: "Cristalino", pole: "Irradiador",
    weapons: ["Espada Mágica de Freyr", "Arco e Flecha Élfico"], being: "Elfos",
    kw: ["pureza", "elevação", "força vital", "elfos"], intent: ["Cura", "Proteção", "Elevação"],
    essence: "Senhor dos Elfos e da força vital. A sua espada tem vontade própria e rompe o que drena a energia. Bom para cura de enfraquecimento, foco e renovação.",
    deep: "Freyr é o Senhor dos Elfos, um deus pacífico ligado à fertilidade e à força vital. A sua Espada Mágica tem vida própria e, quando ativada, procura no baixo astral o que prejudica e causa o mal, rompendo os cordões que drenam a energia da pessoa. Costuma ser chamado em casos de doenças que enfraquecem o corpo, sempre com acompanhamento médico, dando ao mesmo tempo foco, ânimo e a coragem de se renovar. Ensina que, para ganhar algo novo, às vezes é preciso largar o velho.",
    module: "branco",
  },
  {
    id: 1, ed: "Ur", mod: "Uruz", letter: "U", deity: "Audumbla", epi: "Nutrição da Mãe-Terra", type: "Divindade",
    elem: "Terreno", pole: "Neutro", weapons: [], being: null,
    kw: ["nutrição", "vigor", "mãe-terra", "base"], intent: ["Cura", "Harmonia"],
    essence: "A vaca primordial, a Mãe-Terra. Energia nutritiva que dá vigor e base, ampara a carência e traz segurança quando nos sentimos sós.",
    module: "branco",
  },
  {
    id: 2, ed: "Thorn", mod: "Thurisaz", letter: "TH", deity: "Thorn", epi: "O Senhor das Batalhas", type: "Deus",
    elem: "Eólico", pole: "Irradiador",
    weapons: ["Martelo Mjolnir", "Cinturão Megingjard"], being: null,
    kw: ["batalha", "iniciativa", "determinação", "proteção"], intent: ["Proteção", "Coragem"],
    essence: "O senhor das batalhas justas. Determinação e iniciativa para lutar as verdadeiras batalhas da vida e para iniciar projetos. Fulminante contra o astral inferior.",
    deep: "Thorn (Thor) é o senhor das batalhas, sinónimo de bravura e determinação. A sua energia não provoca conflitos: dá força para lutar as verdadeiras batalhas da vida e para iniciar projetos. Traz duas armas, o Martelo Mjolnir, que desfere raios e é fulminante contra o astral inferior, e o Cinturão Megingjard, que dobra a sua força. Chama-se Thorn quando é preciso iniciativa, proteção forte e combate a espíritos que atormentam.",
    module: "branco",
  },
  {
    id: 3, ed: "Ansur", mod: "Ansuz", letter: "A", deity: "Bragi", epi: "Comunicação", type: "Deus",
    elem: "Vegetal", pole: "Neutro", weapons: [], being: null,
    kw: ["comunicação", "poesia", "eloquência", "paz"], intent: ["Comunicação", "Harmonia"],
    essence: "Deus da comunicação, da música e da poesia. Traz eloquência e paz, e desfaz inimizades nascidas de desentendimentos.",
    module: "branco",
  },
  {
    id: 4, ed: "Rad", mod: "Raido", letter: "R", deity: "Siegfried", epi: "Busca e mudança", type: "Herói",
    elem: "Ígneo", pole: "Irradiador",
    weapons: ["Espada Balmung", "Armadura dos Dragões"], being: "Dragões",
    kw: ["busca", "direcionamento", "viagem", "mudança"], intent: ["Proteção", "Transformação", "Coragem"],
    essence: "Herói que se banhou no sangue do dragão. Força da busca e do direcionamento, proteção em viagens e desbloqueio do que está preso.",
    module: "branco",
  },
  {
    id: 5, ed: "Ken", mod: "Kenaz", letter: "C, K", deity: "Loki", epi: "Fogo e Magia", type: "Deus",
    elem: "Vazio", pole: "Absorvedor", weapons: [], being: null,
    kw: ["transformação", "ilusão", "ego", "fogo"], intent: ["Transformação", "Limpeza"],
    essence: "Senhor das formas e do fogo. Transformação íntima, desfaz ilusões e o ego inflamado, queima o negativo. Cuidado com dívidas cármicas.",
    module: "branco",
  },
  {
    id: 6, ed: "Geofu", mod: "Gebo", letter: "G", deity: "Freya", epi: "Feminilidade e Estímulo", type: "Deus",
    elem: "Aquático", pole: "Absorvedor",
    weapons: ["Colar de Brisingamen"], being: null,
    kw: ["feminilidade", "amor", "beleza", "sexualidade"], intent: ["Amor", "Cura"],
    essence: "Deusa do amor e da beleza. Feminilidade, cura de questões femininas e sexuais, restaura o que ficou deformado por sofrimento.",
    module: "branco",
  },
  {
    id: 7, ed: "Wynn", mod: "Wunjo", letter: "V, W", deity: "Wayland", epi: "O Senhor da Arte de Forjar", type: "Deus",
    elem: "Mineral", pole: "Absorvedor", weapons: [], being: "Anões",
    kw: ["forja", "transformação", "amor pessoal", "diamantes internos"], intent: ["Transformação"],
    essence: "O deus-ferreiro. Forja e lapida a pessoa em três fases e revela os diamantes internos. Transformação e desenvolvimento do amor pessoal.",
    module: "branco",
  },
  {
    id: 8, ed: "Hagall", mod: "Hagalaz", letter: "H", deity: "Ymir", epi: "Sabedoria da Terra", type: "Gigante",
    elem: "Terreno", pole: "Irradiador", weapons: [], being: "Gigantes",
    kw: ["sabedoria", "tempo", "eras", "pés no chão"], intent: ["Sabedoria", "Harmonia"],
    essence: "O gigante primordial, a força da terra e das eras. Sabedoria do tempo, maturidade e pés no chão quando nos sentimos perdidos.",
    module: "branco",
  },
  {
    id: 9, ed: "Nied", mod: "Nauthiz", letter: "N", deity: "Hela", epi: "O Vazio", type: "Divindade",
    elem: "Vazio", pole: "Neutro", weapons: [], being: "Espectros",
    kw: ["morte do negativo", "esgotamento", "limpeza", "vazio"], intent: ["Limpeza"],
    essence: "Senhora do vazio, justa e bondosa. Esgota o negativo sem sofrimento. Excelente para limpeza profunda, pessoal e de ambientes.",
    module: "branco",
  },
  {
    id: 10, ed: "Is", mod: "Isa", letter: "I", deity: "Borr", epi: "Pai do Gelo", type: "Divindade",
    elem: "Aquático", pole: "Irradiador", weapons: [], being: null,
    kw: ["congelamento", "maturidade", "pausa", "aviso"], intent: ["Sabedoria"],
    essence: "O pai do gelo. Congela o que flui por vias negativas, uma trava que avisa. Ajuda a amadurecer decisões e a refletir.",
    module: "branco",
  },
  {
    id: 11, ed: "Jara", mod: "Jera", letter: "J, Y", deity: "Sif", epi: "Guerreira da Prosperidade", type: "Deus",
    elem: "Mineral", pole: "Irradiador", weapons: [], being: null,
    kw: ["prosperidade", "habilidade", "destreza", "vocação"], intent: ["Prosperidade"],
    essence: "A guerreira da prosperidade. Habilidade e destreza em vez de força bruta. Abre caminhos, revela a vocação e a verdadeira riqueza.",
    module: "branco",
  },
  {
    id: 12, ed: "Yr", mod: "Eihwaz", letter: "EI", deity: "Yggdrasil", epi: "O Eixo da Vida", type: "Divindade",
    elem: "Vegetal", pole: "Absorvedor", weapons: [], being: "Ents",
    kw: ["eixo", "crescimento", "conhecimento", "chackras"], intent: ["Sabedoria", "Cura"],
    essence: "A árvore-mundos, o eixo da vida. Luz do conhecimento, realinha os chackras. Ótima no início de um atendimento e para crescer.",
    module: "branco",
  },
  {
    id: 13, ed: "Peorth", mod: "Perth", letter: "P", deity: "Nornas", epi: "Deusas do Destino", type: "Divindade",
    elem: "Temporal", pole: "Neutro", weapons: [], being: null,
    kw: ["destino", "leis divinas", "Urd, Verdandi, Skuld", "oculto"], intent: ["Destino", "Sabedoria"],
    essence: "As deusas do destino: Urd (passado), Verdandi (presente) e Skuld (futuro). Regem as Leis Divinas, revelam o oculto e ajudam com as pendências.",
    module: "branco",
  },
  {
    id: 14, ed: "Eolh", mod: "Algiz", letter: "Z", deity: "Heimdall", epi: "O Guardião", type: "Deus",
    elem: "Eólico", pole: "Absorvedor",
    weapons: ["Espada Hofund"], being: null,
    kw: ["guardião", "proteção", "sentidos", "defesa"], intent: ["Proteção"],
    essence: "O guardião de sentidos aguçados. Proteção e limpeza, aguça a visão e a audição espiritual e defende contra ataques.",
    module: "branco",
  },
  {
    id: 15, ed: "Sigel", mod: "Sowilo", letter: "S", deity: "Sigel", epi: "A Glória Solar", type: "Deus",
    elem: "Ígneo", pole: "Neutro", weapons: [], being: null,
    kw: ["sol", "energização", "chackras", "sentimentos"], intent: ["Cura", "Elevação"],
    essence: "A glória solar. Energiza e mantém os nove chackras em equilíbrio, e cuida das emanações sentimentais.",
    module: "branco",
  },
  {
    id: 16, ed: "Tyr", mod: "Tiwaz", letter: "T", deity: "Tyr", epi: "Coragem e Justiça", type: "Deus",
    elem: "Ígneo", pole: "Absorvedor", weapons: [], being: null,
    kw: ["justiça", "coragem", "honra", "juramentos"], intent: ["Coragem"],
    essence: "Deus da justiça, da coragem e dos juramentos. Encoraja quem está de cabeça baixa e ceifa falsidades e ilusões.",
    module: "branco",
  },
  {
    id: 17, ed: "Beorc", mod: "Berkano", letter: "B", deity: "Frigga", epi: "Lar e Família", type: "Deus",
    elem: "Mineral", pole: "Neutro", weapons: [], being: null,
    kw: ["lar", "família", "maternidade", "matrimónio"], intent: ["Harmonia", "Amor"],
    essence: "A deusa-mãe do lar. Harmonia familiar e conjugal, desfaz amarrações e separações, e ampara a maternidade.",
    module: "branco",
  },
  {
    id: 18, ed: "Eoh", mod: "Ehwaz", letter: "E", deity: "Valquíria", epi: "Elevação através da Batalha", type: "Divindade",
    elem: "Eólico", pole: "Neutro", weapons: [], being: "Valquírias",
    kw: ["elevação", "recomeço", "merecimento", "vício"], intent: ["Elevação"],
    essence: "A elevação através da batalha. Reergue quem caiu, dá a outra chance e ânimo para recomeçar, e ampara quem sai do vício.",
    module: "branco",
  },
  {
    id: 19, ed: "Mann", mod: "Mannaz", letter: "M", deity: "Ask e Embla", epi: "Divindades Humanas", type: "Herói",
    elem: "Vegetal", pole: "Irradiador", weapons: [], being: null,
    kw: ["consciência", "bom senso", "autoconhecimento"], intent: ["Sabedoria"],
    essence: "Os primeiros humanos, o fator humano-divino. Desperta a consciência e o bom senso, e limpa o mental para decidir com clareza.",
    module: "branco",
  },
  {
    id: 20, ed: "Lagu", mod: "Laguz", letter: "L", deity: "Njord", epi: "Deus dos Mares", type: "Deus",
    elem: "Aquático", pole: "Neutro", weapons: [], being: "Sereias",
    kw: ["mar", "fluir", "sentimentos", "desbloqueio"], intent: ["Limpeza", "Harmonia"],
    essence: "O deus dos mares. Abundância que limpa e expulsa o que não pertence, desfaz bloqueios e faz os projetos fluir.",
    module: "branco",
  },
  {
    id: 21, ed: "Ing", mod: "Ingwaz", letter: "NG", deity: "Ing", epi: "A Ressurreição", type: "Herói",
    elem: "Cristalino", pole: "Absorvedor", weapons: [], being: null,
    kw: ["ressurreição", "recomeço", "cicatrizes espirituais", "magnitude"], intent: ["Elevação", "Cura"],
    essence: "O deus-herói da ressurreição. Faz renascer o que se dava por perdido, cura as cicatrizes espirituais. Um grandioso recomeço.",
    module: "branco",
  },
  {
    id: 22, ed: "Daeg", mod: "Dagaz", letter: "D", deity: "Baldur", epi: "A Luz nas Sombras", type: "Deus",
    elem: "Terreno", pole: "Absorvedor", weapons: [], being: "Elementares",
    kw: ["passagem", "mudança", "luz nas trevas", "almas perdidas"], intent: ["Cura", "Limpeza"],
    essence: "A luz nas sombras, o senhor das passagens. Muda estados, inclusive para a cura, resgata almas perdidas e limpa locais mal-assombrados.",
    module: "branco",
  },
  {
    id: 23, ed: "Othel", mod: "Othila", letter: "O", deity: "Nove Mundos", epi: "As Esferas", type: "Divindade",
    elem: "Temporal", pole: "Irradiador", weapons: [], being: null,
    kw: ["esferas", "auras protetoras", "escudos", "elementos"], intent: ["Proteção"],
    essence: "As esferas, geradora das auras protetoras. Ativada com cada elemento gera um escudo diferente. Proteção por excelência.",
    module: "branco",
  },
  {
    id: 24, ed: "Wyrd", mod: "— (runa branca)", letter: "—", deity: "Odin", epi: "Liderança", type: "Deus",
    elem: "Tríade", pole: "Tríade",
    weapons: ["Lança Gungnir"], being: null,
    kw: ["liderança de si", "sabedoria", "sacrifício do ego", "totalidade"], intent: ["Sabedoria", "Elevação"],
    essence: "O deus da totalidade e da liderança de si. Descobriu as Runas. Aqui o sacrifício é o do ego, nunca de animais. Congrega e comanda a magia.",
    module: "branco",
  },
];

export const runeById = (id: number): Rune | undefined =>
  RUNES.find((r) => r.id === id);
